/* win32/config.h -- the configuration Makefile.w32 builds against.
 *
 * Generated by win32/regen-config.sh from the output of configure, and
 * checked in so that the tree can be built with nothing but GNU make
 * and a MinGW-w64 compiler.  Do not edit it by hand: run the script
 * again after changing configure.ac or updating the bundled neon.
 *
 * PACKAGE_VERSION is deliberately absent.  The version lives in the
 * VERSION file at the top of the tree and reaches both build paths from
 * there, so that a release cannot report one number under autotools and
 * another here.
 */

/* config.h.  Generated from config.h.in by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define if building universal (internal helper macro) */
/* #undef AC_APPLE_UNIVERSAL_BUILD */

/* Define to specific EGD socket path */
/* #undef EGD_PATH */

/* Define if EGD should be supported */
/* #undef ENABLE_EGD */

/* Define to enable netrc support */
#define ENABLE_NETRC 1

/* Define if GSS_C_NT_HOSTBASED_SERVICE is not defined otherwise */
/* #undef GSS_C_NT_HOSTBASED_SERVICE */

/* Define if you have the add_history function */
#define HAVE_ADD_HISTORY 1

/* Define to 1 if you have the <alloca.h> header file. */
/* #undef HAVE_ALLOCA_H */

/* Define to 1 if you have the <arpa/inet.h> header file. */
/* #undef HAVE_ARPA_INET_H */

/* Define to 1 if you have the 'ASN1_TIME_to_tm' function. */
#define HAVE_ASN1_TIME_TO_TM 1

/* Define to 1 if you have the 'CRYPTO_set_idptr_callback' function. */
/* #undef HAVE_CRYPTO_SET_IDPTR_CALLBACK */

/* Define to 1 if you have the declaration of 'h_errno', and to 0 if you
   don't. */
#define HAVE_DECL_H_ERRNO 0

/* Define to 1 if you have the declaration of 'stpcpy', and to 0 if you don't.
   */
/* #undef HAVE_DECL_STPCPY */

/* Define to 1 if you have the declaration of 'strerror_r', and to 0 if you
   don't. */
#define HAVE_DECL_STRERROR_R 0

/* Define to 1 if you have the <dirent.h> header file, and it defines 'DIR'.
   */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* Define if you have expat */
#define HAVE_EXPAT 1

/* Define to 1 if you have the 'explicit_bzero' function. */
/* #undef HAVE_EXPLICIT_BZERO */

/* Define to 1 if you have the 'fchmod' function. */
/* #undef HAVE_FCHMOD */

/* Define to 1 if you have the 'fcntl' function. */
/* #undef HAVE_FCNTL */

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the 'fstat64' function. */
/* #undef HAVE_FSTAT64 */

/* Define to 1 if you have the 'gai_strerror' function. */
/* #undef HAVE_GAI_STRERROR */

/* Define to 1 if you have the 'getnameinfo' function. */
/* #undef HAVE_GETNAMEINFO */

/* Define to 1 if you have the 'getpass' function. */
/* #undef HAVE_GETPASS */

/* Define to 1 if you have the 'getrandom' function. */
/* #undef HAVE_GETRANDOM */

/* Define to 1 if you have the 'getsockopt' function. */
/* #undef HAVE_GETSOCKOPT */

/* Define to 1 if you have the 'gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the 'gmtime_r' function. */
/* #undef HAVE_GMTIME_R */

/* Define if GnuTLS support is enabled */
/* #undef HAVE_GNUTLS */

/* Define to 1 if you have the 'gnutls_certificate_get_issuer' function. */
/* #undef HAVE_GNUTLS_CERTIFICATE_GET_ISSUER */

/* Define to 1 if you have the 'gnutls_certificate_get_x509_cas' function. */
/* #undef HAVE_GNUTLS_CERTIFICATE_GET_X509_CAS */

/* Define to 1 if you have the 'gnutls_certificate_set_retrieve_function2'
   function. */
/* #undef HAVE_GNUTLS_CERTIFICATE_SET_RETRIEVE_FUNCTION2 */

/* Define to 1 if you have the 'gnutls_certificate_set_x509_system_trust'
   function. */
/* #undef HAVE_GNUTLS_CERTIFICATE_SET_X509_SYSTEM_TRUST */

/* Define to 1 if you have the 'gnutls_ciphersuite_get' function. */
/* #undef HAVE_GNUTLS_CIPHERSUITE_GET */

/* Define to 1 if you have the 'gnutls_privkey_import_ext' function. */
/* #undef HAVE_GNUTLS_PRIVKEY_IMPORT_EXT */

/* Define to 1 if you have the 'gnutls_session_get_data2' function. */
/* #undef HAVE_GNUTLS_SESSION_GET_DATA2 */

/* Define to 1 if you have the 'gnutls_set_default_priority_append' function.
   */
/* #undef HAVE_GNUTLS_SET_DEFAULT_PRIORITY_APPEND */

/* Define to 1 if you have the 'gnutls_x509_crt_equals' function. */
/* #undef HAVE_GNUTLS_X509_CRT_EQUALS */

/* Define to 1 if you have the 'gnutls_x509_crt_sign2' function. */
/* #undef HAVE_GNUTLS_X509_CRT_SIGN2 */

/* Define to 1 if you have the 'gnutls_x509_dn_get_rdn_ava' function. */
/* #undef HAVE_GNUTLS_X509_DN_GET_RDN_AVA */

/* Define if GSSAPI support is enabled */
/* #undef HAVE_GSSAPI */

/* Define to 1 if you have the <gssapi/gssapi_generic.h> header file. */
/* #undef HAVE_GSSAPI_GSSAPI_GENERIC_H */

/* Define to 1 if you have the <gssapi/gssapi.h> header file. */
/* #undef HAVE_GSSAPI_GSSAPI_H */

/* Define to 1 if you have the <gssapi.h> header file. */
/* #undef HAVE_GSSAPI_H */

/* Define to 1 if you have the 'gss_init_sec_context' function. */
/* #undef HAVE_GSS_INIT_SEC_CONTEXT */

/* Define to 1 if you have the <history.h> header file. */
/* #undef HAVE_HISTORY_H */

/* Define to 1 if you have the 'hstrerror' function. */
/* #undef HAVE_HSTRERROR */

/* Define to 1 if you have the 'iconv' function. */
#define HAVE_ICONV 1

/* Define to 1 if you have the <iconv.h> header file. */
#define HAVE_ICONV_H 1

/* Define to 1 if you have the 'if_indextoname' function. */
/* #undef HAVE_IF_INDEXTONAME */

/* Define to 1 if you have the 'if_nametoindex' function. */
/* #undef HAVE_IF_NAMETOINDEX */

/* Define to 1 if you have the 'inet_ntop' function. */
/* #undef HAVE_INET_NTOP */

/* Define to 1 if you have the 'inet_pton' function. */
/* #undef HAVE_INET_PTON */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <langinfo.h> header file. */
/* #undef HAVE_LANGINFO_H */

/* Define to 1 if you have the <libintl.h> header file. */
#define HAVE_LIBINTL_H 1

/* Define if libproxy is supported */
/* #undef HAVE_LIBPROXY */

/* Define if you have the readline library */
#define HAVE_LIBREADLINE 1

/* Define if you have libxml */
/* #undef HAVE_LIBXML */

/* Define to 1 if you have the <libxml/parser.h> header file. */
/* #undef HAVE_LIBXML_PARSER_H */

/* Define to 1 if you have the <libxml/xmlversion.h> header file. */
/* #undef HAVE_LIBXML_XMLVERSION_H */

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* Define to 1 if you have the 'lseek64' function. */
#define HAVE_LSEEK64 1

/* Define to 1 if you have the 'memcpy' function. */
#define HAVE_MEMCPY 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <minix/config.h> header file. */
/* #undef HAVE_MINIX_CONFIG_H */

/* Define to 1 if you have the 'mkstemp' function. */
#define HAVE_MKSTEMP 1

/* Define to 1 if you have the <ndir.h> header file, and it defines 'DIR'. */
/* #undef HAVE_NDIR_H */

/* Define to 1 if you have the <netdb.h> header file. */
/* #undef HAVE_NETDB_H */

/* Define to 1 if you have the <netinet/in.h> header file. */
/* #undef HAVE_NETINET_IN_H */

/* Define to 1 if you have the <netinet/tcp.h> header file. */
/* #undef HAVE_NETINET_TCP_H */

/* Define to 1 if you have the <net/if.h> header file. */
/* #undef HAVE_NET_IF_H */

/* Define to 1 if you have the 'nl_langinfo' function. */
/* #undef HAVE_NL_LANGINFO */

/* Define if OpenSSL support is enabled */
#define HAVE_OPENSSL 1

/* Enable OpenSSL 1.1 support */
#define HAVE_OPENSSL11 1

/* Define to 1 if you have the <openssl/opensslv.h> header file. */
#define HAVE_OPENSSL_OPENSSLV_H 1

/* Define to 1 if you have the <openssl/ssl.h> header file. */
#define HAVE_OPENSSL_SSL_H 1

/* Define if pakchois library supported */
/* #undef HAVE_PAKCHOIS */

/* Define to 1 if you have the 'poll' function. */
/* #undef HAVE_POLL */

/* Define to 1 if you have the 'pthread_mutex_init' function. */
/* #undef HAVE_PTHREAD_MUTEX_INIT */

/* Define to 1 if you have the 'pthread_mutex_lock' function. */
/* #undef HAVE_PTHREAD_MUTEX_LOCK */

/* Define to 1 if you have the <pwd.h> header file. */
/* #undef HAVE_PWD_H */

/* Define to 1 if you have the <readline.h> header file. */
/* #undef HAVE_READLINE_H */

/* Define to 1 if you have the <readline/history.h> header file. */
#define HAVE_READLINE_HISTORY_H 1

/* Define to 1 if you have the <readline/readline.h> header file. */
#define HAVE_READLINE_READLINE_H 1

/* Define to 1 if you have the 'rl_completion_matches' function. */
#define HAVE_RL_COMPLETION_MATCHES 1

/* Define to 1 if you have the 'secure_getenv' function. */
/* #undef HAVE_SECURE_GETENV */

/* Define to 1 if you have the 'sendmsg' function. */
/* #undef HAVE_SENDMSG */

/* Define to 1 if you have the 'setlocale' function. */
#define HAVE_SETLOCALE 1

/* Define to 1 if you have the 'setsockopt' function. */
/* #undef HAVE_SETSOCKOPT */

/* Define to 1 if you have the 'setvbuf' function. */
#define HAVE_SETVBUF 1

/* Define to 1 if you have the <sgtty.h> header file. */
/* #undef HAVE_SGTTY_H */

/* Define to 1 if you have the 'signal' function. */
#define HAVE_SIGNAL 1

/* Define to 1 if you have the <signal.h> header file. */
#define HAVE_SIGNAL_H 1

/* Define to 1 if the system has the type 'socklen_t'. */
#define HAVE_SOCKLEN_T 1

/* Define to 1 if you have the 'SSL_CIPHER_standard_name' function. */
#define HAVE_SSL_CIPHER_STANDARD_NAME 1

/* Define to 1 if you have the 'SSL_SESSION_cmp' function. */
/* #undef HAVE_SSL_SESSION_CMP */

/* Define to 1 if you have the <stdarg.h> header file. */
#define HAVE_STDARG_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the 'stpcpy' function. */
/* #undef HAVE_STPCPY */

/* Define to 1 if you have the 'strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define to 1 if you have the 'strcoll' function. */
#define HAVE_STRCOLL 1

/* Define to 1 if you have the 'strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the 'strerror' function. */
#define HAVE_STRERROR 1

/* Define if you have 'strerror_r'. */
/* #undef HAVE_STRERROR_R */

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the 'strtoll' function. */
#define HAVE_STRTOLL 1

/* Define to 1 if you have the 'strtoq' function. */
/* #undef HAVE_STRTOQ */

/* Define to 1 if you have the 'strtoull' function. */
#define HAVE_STRTOULL 1

/* Define to 1 if 'd_ino' is a member of 'struct dirent'. */
#define HAVE_STRUCT_DIRENT_D_INO 1

/* Define to 1 if 'd_type' is a member of 'struct dirent'. */
/* #undef HAVE_STRUCT_DIRENT_D_TYPE */

/* Define to 1 if 'tm_gmtoff' is a member of 'struct tm'. */
/* #undef HAVE_STRUCT_TM_TM_GMTOFF */

/* Define to 1 if '__tm_gmtoff' is a member of 'struct tm'. */
/* #undef HAVE_STRUCT_TM___TM_GMTOFF */

/* Define to 1 if you have the <sys/dir.h> header file, and it defines 'DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/limits.h> header file. */
/* #undef HAVE_SYS_LIMITS_H */

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines 'DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Define to 1 if you have the <sys/poll.h> header file. */
/* #undef HAVE_SYS_POLL_H */

/* Define to 1 if you have the <sys/select.h> header file. */
/* #undef HAVE_SYS_SELECT_H */

/* Define to 1 if you have the <sys/socket.h> header file. */
/* #undef HAVE_SYS_SOCKET_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/uio.h> header file. */
/* #undef HAVE_SYS_UIO_H */

/* Define to 1 if you have the 'tcsetattr' function. */
/* #undef HAVE_TCSETATTR */

/* Define to 1 if you have the <termios.h> header file. */
/* #undef HAVE_TERMIOS_H */

/* Define to 1 if you have the <termio.h> header file. */
/* #undef HAVE_TERMIO_H */

/* Define to 1 if you have the 'timegm' function. */
/* #undef HAVE_TIMEGM */

/* Define if the timezone global is available */
#define HAVE_TIMEZONE 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if the system has the type 'unsigned long long int'. */
#define HAVE_UNSIGNED_LONG_LONG_INT 1

/* Define to 1 if you have the <wchar.h> header file. */
#define HAVE_WCHAR_H 1

/* Define to 1 if you have the <wspiapi.h> header file. */
#define HAVE_WSPIAPI_H 1

/* Define to be the neon version string */
#define NEON_VERSION "0.37.1"

/* Define to enable debugging */
#define NE_DEBUGGING 1

/* Define to be printf format string for ne_off_t */
#define NE_FMT_NE_OFF_T NE_FMT_OFF64_T

/* Define to be printf format string for off64_t */
#define NE_FMT_OFF64_T "lld"

/* Define to be printf format string for off_t */
#define NE_FMT_OFF_T "ld"

/* Define to be printf format string for size_t */
#define NE_FMT_SIZE_T "llu"

/* Define to be printf format string for ssize_t */
#define NE_FMT_SSIZE_T "lld"

/* Define to be printf format string for time_t */
#define NE_FMT_TIME_T "lld"

/* Define to be printf format string for XML_Size */
#define NE_FMT_XML_SIZE "ld"

/* Defined if DAV is supported */
#define NE_HAVE_DAV 1

/* Defined if GSSAPI is supported */
/* #undef NE_HAVE_GSSAPI */

/* Defined if I18N is supported */
/* #undef NE_HAVE_I18N */

/* Defined if IPV6 is supported */
/* #undef NE_HAVE_IPV6 */

/* Defined if LFS is supported */
#define NE_HAVE_LFS 1

/* Defined if LIBPXY is supported */
/* #undef NE_HAVE_LIBPXY */

/* Defined if NTLM is supported */
/* #undef NE_HAVE_NTLM */

/* Defined if SSL is supported */
#define NE_HAVE_SSL 1

/* Defined if TS_SSL is supported */
#define NE_HAVE_TS_SSL 1

/* Defined if ZLIB is supported */
/* #undef NE_HAVE_ZLIB */

/* Define to be filename of an SSL CA root bundle */
/* #undef NE_SSL_CA_BUNDLE */

/* Define if poll() should be used */
/* #undef NE_USE_POLL */

/* Define to be neon library major version */
#define NE_VERSION_MAJOR (0)

/* Define to be neon library minor version */
#define NE_VERSION_MINOR (37)

/* Define to be neon library patch version */
#define NE_VERSION_PATCH (1)

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "cadaver"

/* Define to the full name and version of this package. */

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "cadaver"

/* Define to the home page for this package. */
#define PACKAGE_URL "https://github.com/Azathothas/cadaver-windows"

/* Define to the version of this package. */

/* The size of 'int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of 'long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* The size of 'long long', as computed by sizeof. */
#define SIZEOF_LONG_LONG 8

/* The size of 'off64_t', as computed by sizeof. */
#define SIZEOF_OFF64_T 8

/* The size of 'off_t', as computed by sizeof. */
#define SIZEOF_OFF_T 4

/* The size of 'size_t', as computed by sizeof. */
#define SIZEOF_SIZE_T 8

/* The size of 'ssize_t', as computed by sizeof. */
#define SIZEOF_SSIZE_T 8

/* The size of 'time_t', as computed by sizeof. */
#define SIZEOF_TIME_T 8

/* The size of 'XML_Size', as computed by sizeof. */
#define SIZEOF_XML_SIZE 4

/* Define to 1 if all of the C89 standard headers exist (not just the ones
   required in a freestanding environment). This macro is provided for
   backward compatibility; new code need not use it. */
#define STDC_HEADERS 1

/* Define to 1 if strerror_r returns char *. */
/* #undef STRERROR_R_CHAR_P */

/* Define if getaddrinfo supports AI_ADDRCONFIG */
/* #undef USE_GAI_ADDRCONFIG */

/* Define if getaddrinfo() should be used */
/* #undef USE_GETADDRINFO */

/* Enable extensions on AIX, Interix, z/OS.  */
#ifndef _ALL_SOURCE
# define _ALL_SOURCE 1
#endif
/* Enable extensions on Cosmopolitan Libc. */
#ifndef _COSMO_SOURCE
# define _COSMO_SOURCE 1
#endif
/* Enable general extensions on macOS.  */
#ifndef _DARWIN_C_SOURCE
# define _DARWIN_C_SOURCE 1
#endif
/* Enable general extensions on Solaris.  */
#ifndef __EXTENSIONS__
# define __EXTENSIONS__ 1
#endif
/* Enable GNU extensions on systems that have them.  */
#ifndef _GNU_SOURCE
# define _GNU_SOURCE 1
#endif
/* Enable X/Open compliant socket functions that do not require linking
   with -lxnet on HP-UX 11.11.  */
#ifndef _HPUX_ALT_XOPEN_SOCKET_API
# define _HPUX_ALT_XOPEN_SOCKET_API 1
#endif
/* Identify the host operating system as Minix.
   This macro does not affect the system headers' behavior.
   A future release of Autoconf may stop defining this macro.  */
#ifndef _MINIX
/* # undef _MINIX */
#endif
/* Enable general extensions on NetBSD.
   Enable NetBSD compatibility extensions on Minix.  */
#ifndef _NETBSD_SOURCE
# define _NETBSD_SOURCE 1
#endif
/* Enable OpenBSD compatibility extensions on NetBSD.
   Oddly enough, this does nothing on OpenBSD.  */
#ifndef _OPENBSD_SOURCE
# define _OPENBSD_SOURCE 1
#endif
/* Define to 1 if needed for POSIX-compatible behavior.  */
#ifndef _POSIX_SOURCE
/* # undef _POSIX_SOURCE */
#endif
/* Define to 2 if needed for POSIX-compatible behavior.  */
#ifndef _POSIX_1_SOURCE
/* # undef _POSIX_1_SOURCE */
#endif
/* Enable POSIX-compatible threading on Solaris.  */
#ifndef _POSIX_PTHREAD_SEMANTICS
# define _POSIX_PTHREAD_SEMANTICS 1
#endif
/* Enable extensions specified by ISO/IEC TS 18661-5:2014.  */
#ifndef __STDC_WANT_IEC_60559_ATTRIBS_EXT__
# define __STDC_WANT_IEC_60559_ATTRIBS_EXT__ 1
#endif
/* Enable extensions specified by ISO/IEC TS 18661-1:2014.  */
#ifndef __STDC_WANT_IEC_60559_BFP_EXT__
# define __STDC_WANT_IEC_60559_BFP_EXT__ 1
#endif
/* Enable extensions specified by ISO/IEC TS 18661-2:2015.  */
#ifndef __STDC_WANT_IEC_60559_DFP_EXT__
# define __STDC_WANT_IEC_60559_DFP_EXT__ 1
#endif
/* Enable extensions specified by C23 Annex F.  */
#ifndef __STDC_WANT_IEC_60559_EXT__
# define __STDC_WANT_IEC_60559_EXT__ 1
#endif
/* Enable extensions specified by ISO/IEC TS 18661-4:2015.  */
#ifndef __STDC_WANT_IEC_60559_FUNCS_EXT__
# define __STDC_WANT_IEC_60559_FUNCS_EXT__ 1
#endif
/* Enable extensions specified by C23 Annex H and ISO/IEC TS 18661-3:2015.  */
#ifndef __STDC_WANT_IEC_60559_TYPES_EXT__
# define __STDC_WANT_IEC_60559_TYPES_EXT__ 1
#endif
/* Enable extensions specified by ISO/IEC TR 24731-2:2010.  */
#ifndef __STDC_WANT_LIB_EXT2__
# define __STDC_WANT_LIB_EXT2__ 1
#endif
/* Enable extensions specified by ISO/IEC 24747:2009.  */
#ifndef __STDC_WANT_MATH_SPEC_FUNCS__
# define __STDC_WANT_MATH_SPEC_FUNCS__ 1
#endif
/* Enable extensions on HP NonStop.  */
#ifndef _TANDEM_SOURCE
# define _TANDEM_SOURCE 1
#endif
/* Enable X/Open extensions.  Define to 500 only if necessary
   to make mbstate_t available.  */
#ifndef _XOPEN_SOURCE
/* # undef _XOPEN_SOURCE */
#endif


/* Define WORDS_BIGENDIAN to 1 if your processor stores words with the most
   significant byte first (like Motorola and SPARC, unlike Intel). */
#if defined AC_APPLE_UNIVERSAL_BUILD
# if defined __BIG_ENDIAN__
#  define WORDS_BIGENDIAN 1
# endif
#else
# ifndef WORDS_BIGENDIAN
/* #  undef WORDS_BIGENDIAN */
# endif
#endif

/* Define to enable GNU extensions */
#define _GNU_SOURCE 1

/* Define to empty if 'const' does not conform to ANSI C. */
/* #undef const */

/* Define if in_addr_t is not available */
#define in_addr_t unsigned int

/* Define to '__inline__' or '__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to 'long int' if <sys/types.h> does not define. */
/* #undef off_t */

/* Define as 'unsigned int' if <stddef.h> doesn't define. */
/* #undef size_t */

/* Define if socklen_t is not available */
/* #undef socklen_t */

#if defined(HAVE_STPCPY) && defined(HAVE_DECL_STPCPY) && !HAVE_DECL_STPCPY && !defined(stpcpy)
char *stpcpy(char *, const char *);
#endif

/* #undef NE_MINIMUM_VERSION */
#define NE_MINIMUM_VERSION(majv_, minv_) \
    (((majv_) == NE_VERSION_MAJOR && NE_VERSION_MINOR >= (minv_)) \
     || NE_VERSION_MAJOR > (majv_))

