#!/bin/sh
# Regenerates win32/config.h, the configuration Makefile.w32 builds
# against.
#
#   ./win32/regen-config.sh
#
# Makefile.w32 exists so that cadaver can be built with nothing but GNU
# make and a compiler.  It still needs the answers configure would have
# worked out, so those are checked in.  Rather than copying config.h by
# hand after every change to configure.ac or to the bundled neon, this
# runs configure in a scratch directory -- leaving any build in the
# source tree alone -- and rewrites the result.
#
# Two things are taken out of the generated file:
#
#   PACKAGE_VERSION and PACKAGE_STRING, because the version lives in
#   VERSION and reaches both build paths from there.  Leaving a copy
#   here would let the two disagree.
#
# Run it from the top of the tree in an MSYS2 UCRT64 shell, with the
# same OpenSSL and expat the build will use: the answers about those
# two are baked into the result.

set -e

srcdir=`dirname "$0"`/..
cd "$srcdir"
srcdir=`pwd`

if [ ! -x ./configure ]; then
    echo "-- Running autogen.sh --"
    ./autogen.sh
fi

build=`mktemp -d 2>/dev/null || echo ./regen-config.$$`
mkdir -p "$build"

cleanup() {
    rm -rf "$build"
}
trap cleanup EXIT INT TERM

echo "-- Configuring in $build --"
(cd "$build" && "$srcdir/configure" --with-ssl=openssl >/dev/null)

echo "-- Writing win32/config.h --"
{
    cat <<'EOF'
/* win32/config.h -- the configuration Makefile.w32 builds against.
 *
 * Generated by win32/regen-config.sh from the output of configure, and
 * checked in so that the tree can be built with nothing but GNU make
 * and a MinGW-w64 compiler.  Do not edit it by hand: run the script
 * again after changing configure.ac or updating the bundled neon.
 *
 * PACKAGE_VERSION is deliberately absent.  The version lives in the
 * VERSION file at the top of the tree and reaches both build paths from
 * there, so that a release cannot report one number under autotools and
 * another here.
 */

EOF
    sed -e '/^#define PACKAGE_VERSION /d' \
        -e '/^#define PACKAGE_STRING /d' \
        "$build/config.h"
} > win32/config.h

echo "-- Done; check the diff before committing --"
